import sketch from 'sketch'
// documentation: https://developer.sketchapp.com/reference/api/

// --
// Main entry
// --

export default function() {
    // Get selected layers
    const doc = sketch.getSelectedDocument()
    const selectedLayers = doc.selectedLayers

    // Show alert if no layers are selected
    if (selectedLayers.length == 0) {
        sketch.UI.alert("No layers selected", "Select a single artboard (or a layer within an artboard) to save the atlas entries as a JSON file")
        return
    }

    // Collect artboards
    var duplicateArtboards = []
    for (var i = 0; i < selectedLayers.length; i++) {
        if (selectedLayers.layers[i].type == "Artboard") {
            duplicateArtboards.push(selectedLayers.layers[i])
        } else if (selectedLayers.layers[i].getParentArtboard()) {
            duplicateArtboards.push(selectedLayers.layers[i].getParentArtboard())
        }
    }

    // Filter out duplicates
    var artboards = duplicateArtboards.filter(function(item, pos, self) {
        for (var i = 0; i < self.length; i++) {
            if (self[i].id == item.id) {
                return i == pos
            }
        }
        return false
    })

    // Abort if no artboard was found
    if (artboards.length == 0) {
        sketch.UI.alert("No artboards found", "The selected layers are not part of an artboard")
        return
    }

    // Also abort if multiple artboards were found
    if (artboards.length > 1) {
        sketch.UI.alert("Multiple artboards selected", "You can only save entries for one artboard at a time")
        return
    }

    // Prepare dialog
    var artboard = artboards[0];
    var dialog = NSSavePanel.savePanel();
    var splitName = artboard.name.split('_');
    for (var i = 0; i < splitName.length; i++) {
        splitName[i] = splitName[i].charAt(0).toUpperCase() + splitName[i].slice(1);
    }
    splitName = splitName.join("").split(' ');
    for (var i = 0; i < splitName.length; i++) {
        splitName[i] = splitName[i].charAt(0).toUpperCase() + splitName[i].slice(1);
    }
    dialog.setNameFieldStringValue(splitName.join(""));
    dialog.allowedContentTypes = [UTType.typeWithFilenameExtension("cs")];

    // Show
    if (dialog.runModal()) {
        saveFile(artboard, dialog.URL().path());
    }
}

var saveFile = function(artboard, path) {
    // Determine filename
    var lastSlash = path.lastIndexOf("/");
    var filename = lastSlash >= 0 ? path.substring(lastSlash + 1) : path;
    var className = filename.charAt(0).toUpperCase() + filename.slice(1);
    var lastDot = className.lastIndexOf(".");
    if (lastDot >= 0) {
        className = className.substring(0, lastDot);
    }

    // Prepare entries
    var entries = []
    var usedWidth = 0
    var usedHeight = 0
    for (var i = 0; i < artboard.layers.length; i++) {
        entries.push({ "identifier": artboard.layers[i].name, "x": Math.floor(artboard.layers[i].frame.x), "y": Math.floor(artboard.layers[i].frame.y), "width": Math.floor(artboard.layers[i].frame.width), "height": Math.floor(artboard.layers[i].frame.height) })
        usedWidth = Math.max(usedWidth, Math.floor(artboard.layers[i].frame.x + artboard.layers[i].frame.width))
        usedHeight = Math.max(usedHeight, Math.floor(artboard.layers[i].frame.y + artboard.layers[i].frame.height))
    }

    // First source code part
    var sourceString = [
        "using System.Collections;",
        "using System.Collections.Generic;",
        "using UnityEngine;",
        "",
        "// Generated by a Sketch texture atlas plugin",
        "public class " + className + " {",
        "",
        "    // --",
        "    // Texture dimensions",
        "    // --",
        "",
        "    public static float usedWidth = " + usedWidth + ";",
        "    public static float usedHeight = " + usedHeight + ";",
        "    public static float totalWidth = " + artboard.frame.width + ";",
        "    public static float totalHeight = " + artboard.frame.height + ";",
        "    public static float paddedWidth = " + getPaddedSize(artboard.frame.width) + ";",
        "    public static float paddedHeight = " + getPaddedSize(artboard.frame.height) + ";",
        "",
        "",
        "    // --",
        "    // Entries",
        "    // --",
        "",
        "    public static Dictionary<string, Entry> entries = new Dictionary<string, Entry>() {"
    ];

    // Add entries
    for (var i = 0; i < entries.length; i++) {
        sourceString.push('        { "' + entries[i]["identifier"] + '", new Entry(' + entries[i]["x"] + ', ' + entries[i]["y"] + ', ' + entries[i]["width"] + ', ' + entries[i]["height"] + ') }' + (i + 1 < entries.length ? ',' : ''));
    }

    // Final source part
    sourceString = sourceString.concat([
        "    };",
        "",
        "",
        "    // --",
        "    // Entry class",
        "    // --",
        "",
        "    public class Entry {",
        "",
        "        public float x;",
        "        public float y;",
        "        public float width;",
        "        public float height;",
        "",
        "        public Entry(float x, float y, float width, float height) {",
        "            this.x = x;",
        "            this.y = y;",
        "            this.width = width;",
        "            this.height = height;",
        "        }",
        "",
        "    }",
        "",
        "}"
    ]);

    // Save source
    const string = NSString.stringWithFormat("%@", sourceString.join("\n"));
    string.writeToFile_atomically(path, true);
}

var getPaddedSize = function(size) {
    return [ 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536 ].find(function(item) { return item >= size } );
}
